ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        port: $PORT

database:
    url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
    user: "root"
    driver: "org.h2.Driver"
    password: ""
